version: "3.9"

services:
  user-data-database:
    image: postgres:latest
    container_name: user-data-database
    restart: always
    networks:
      - user-data
    volumes:
      - user-data-database:/var/lib/postgresql
    env_file:
      - ./database.env
    ports:
      - 5445:5432

networks:
  user-data:
    name: user-data
    driver: bridge

volumes:
  user-data-database:
    driver: local
