version: "3.9"

services:
  user-authentication-database:
    image: postgres:latest
    container_name: user-authentication-database
    restart: always
    ports:
      - 5444:5432
    networks:
      - user-authentication
    volumes:
      - user-authentication-database:/var/lib/postgresql
    env_file:
      - ./database.env

networks:
  user-authentication:
    name: user-authentication
    driver: bridge

volumes:
  user-authentication-database:
    driver: local
  user-authentication-tokens:
    driver: local
